name: ikmb-metagenome-1.1
channels:
  - biobakery
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - bracken
  - picard
  - megahit
  - spades
  - metabat2
  - vamb
  - gtdbtk
  - bbmap
  - bowtie2
  - diamond
  - fastqc
  - humann
  - ipython
  - krakentools
  - samtools
