title: "Metagenomic workflows report"
subtitle: "Best-practice metagenome pipeline"
custom_logo: "ikmblogo.png"
custom_logo_title: "Insitute of Clinical Molecular Biology, Kiel"
custom_logo_url: "http://www.ikmb.uni-kiel.de"

extra_fn_clean_exts:
    - _R1
    - _R2
report_comment: >
    This report has been generated automatically by the IKMB Metagenomic workflows pipeline.

report_header_info:
    - Contact E-mail: "e.wacker@ikmb.uni-kiel.de"
    - Application Type: "Metagenomic workflows"

top_modules:
    - 'general_stats'
